### PR TITLE
Css ecommerce page | Jumanah Almajnouni

### PR DESCRIPTION
**Pull request by Jumanah-A**
Screen Shot 2021-07-05 at 1 18 30 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Jumanah! Your images seem to be overlapping each other, you likely need to set a height and width on them. I would also look into the `object-fit` property if you haven't already:

https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by Jumanah-A** [comment]
> Hey Jumanah! Your images seem to be overlapping each other, you likely need to set a height and width on them. I would also look into the `object-fit` property if you haven't already:
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by Jumanah-A** [comment]
Screen Shot 2021-07-08 at 2 26 53 PM

**Comment by Jumanah-A** [comment]
Screen Shot 2021-07-09 at 11 29 41 AM

**Review by codingcodymiller — APPROVED** [review]

**Pull request merged**
